name: My First Workflow

on: push

jobs:
  first-job:
     runs-on:  ubuntu-latest
     steps:
     - name: welcome-msg
       run: echo "Welcome Satish"

     - name: checkout
       uses: actions/checkout@v4

     - name: List files and read file
       run: |
          ls -ltra
          cat README.md

     - name: Install the library
       run: sudo apt-get install cowsay

     - name: Run cowsay command
       run: cowsay -f dragon "I will snatch your chips" >> dragon.txt

     - name: verify cowsay ASCII file
       run: grep -i snatch dragon.txt

     - name: print ASCII generated file
       run: cat dragon.txt 
