name: My First Workflow
on: push
env:
  username: satish
jobs:
  first-job:
     runs-on:  ubuntu-latest
     steps:
     - name: welcome-msg
       run: echo "Welcome Satish"

     - name: checkout
       uses: actions/checkout@v4

     - name: List files and read file
       run: |
          ls -ltra
          cat README.md

     - name: Run the cowsay_utility shell script
       run: |
          chmod +x cowsay_utility.sh
          ./cowsay_utility.sh
       