name: My First Workflow
on: push
jobs:
  first-job:
     runs: ubuntu-latest
     steps:
     - name: welcome-msg
       run: echo "Welcome Satish"
     - name: List files
       run: ls
     - name: read file
       run: cat README.md
