name: My First Workflow

on: push

jobs:
  first-job:
     runs-on:  ubuntu-latest
     steps:
     - name: welcome-msg
       run: echo "Welcome Satish"

     - name: checkout
       uses: actions/checkout@v4
       
     - name: List files
       run: ls

     - name: read file
       run: cat README.md
